### ISSUE TITLE
是否支持K线图

### ISSUE THREAD

**Issue by zhanshancheng** [antvis/my-f2#12]
昨天测试 my-f2 在支付宝小程序中 好像不支持 Geom 基本类型为 schema(K线图、箱型图)、
不懂是我代码问题还是确实不支持，所以想确认一下。
如果目前不支持、大概什么时候可以支持

**Comment by zhanshancheng** [comment]
按照你这个demo 测试、不管是小程序开发者工具 还是真机预览都显示不出来。
能否在mini-program-f2-demos中添加一个k线图示例进一步进行验证。

**Comment by simaQ** [comment]
如果绘制不出来，请提供具体具体的信息：可运行的代码，使用的 my-f2 的版本等！

我给你的代码，就是在小程序开发者工具上运行过的，基于 @antv/my-f2@1.1.4 版本

**Comment by simaQ** [comment]
例子在这里： https://github.com/antvis/mini-program-f2-demos/tree/stock-chart-demo/pages/charts/stock

运行的时候，你需要在根目录下安装 my-f2 依赖:

```js
npm i @antv/my-f2@1.1.4
```
