### ISSUE TITLE
build/my-f2.js 没跟F2同步

### ISSUE THREAD

**Issue by cydiacen** [antvis/my-f2#13]
* **Link**:https://github.com/antvis/f2/issues/429
* **Platform**:小程序
* **Mini Showcase(like screenshots)**:

my-f2的包里的build/my-f2.js 不是最新版导致圆弧还是没办法使用fillStyle。而小程序内部引用的就是前面提到的文件 每次需要手动去node-module修改 很麻烦

**Comment by simaQ** [comment]
...... 升级到 1.1.5 版本

以后请尽量用的什么库就在什么库上提交 issue，或者说明充分你使用的环境。
