### ISSUE TITLE
你好，请问如何画虚线？

### ISSUE THREAD

**Issue by Surile** [antvis/my-f2#14]
当Value是0的时候，怎么画虚线。柱状图。目前不知道用那个Api，还有怎么自己定义Y。而不是根据value来生成

**Comment by simaQ** [comment]
不明白你在描述什么

**Comment by Surile** [comment]
emmmmmmmm。算了给你截图。
![image](https://user-images.githubusercontent.com/28652894/49632687-9aaa6580-fa31-11e8-822d-79494a9a5b87.png)

**Comment by simaQ** [comment]
1. 『这种怎么画』
直接用 chart.interval() 绘制，然后在 style() 方法中定义图形属性就行了，图形属性参考：https://www.yuque.com/antv/f2/api-g-shape#wh1gte

2. 『这个怎么固定成这样的』
在列定义中定义 ticks

参考此 DEMO: https://codepen.io/Sima/pen/NEQZVW

**Comment by Surile** [comment]
好的。3Q

**Comment by Surile** [comment]
@simaQ    你好，我的需求是值为0的时候，怎么设置虚线。

**Comment by simaQ** [comment]
数值为   0 的话，按照我们的映射规则，柱子的高度是 0，这种场景，你自己使用 chart.guide().line() 绘制就好。
