### ISSUE TITLE
Is it supposed to support  animate and guide?

### ISSUE THREAD

**Issue by NoraGithub** [antvis/my-f2#2]
Is it supposed to support  `animate` and `guide`?
 `animate` and `guide` seems to be unavailable if miniapp is in JSCORE and both of the object/function is DOM-related.

**Comment by simaQ** [comment]
Now, they are supported, you can download `@antv/my-f2@1.0.0-beta.1` and try it, you also can run demos here: https://github.com/antvis/mini-program-f2-demos/tree/master/my-charts
